const actionTypes = {
  GRAFFITI_PAGE_REQUEST: 'GRAFFITI_PAGE_REQUEST',
  GRAFFITI_PAGE_SUCCESS: 'GRAFFITI_PAGE_SUCCESS',
  GRAFFITI_PAGE_ERROR: 'GRAFFITI_PAGE_ERROR',
};

export default actionTypes;
